baseURL = 'https://www.observeautomation.com/'
relativeURLs = true 
canonifyURLs = true 
languageCode = 'en-us'
title = "ObserveAutomation"
theme = "PaperMod"
environment = "production"

[params]
hero_image="/image/Observe Automation Logo Black on white background 2400x1600.webp"
ShowCodeCopyButtons= true

[services]
  [services.googleAnalytics]
    id = "G-4BN5LK4X9N"

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = false

[params.vapi]
publicKey = "9a52eda7-9f64-41f7-9686-29bb583c17d3"      # from dashboard (public)
assistantId = "d3ec99e6-0e5b-4277-8198-688dd495daf0" # from Assistants list

