baseURL = 'https://www.observeautomation.com/'
relativeURLs = true 
canonifyURLs = true 
languageCode = 'en-us'
title = "ObserveAutomation"
theme = "PaperMod"
environment = "production"

[params]
hero_image="/image/Observe Automation Logo Black on white background 2400x1600.png"
ShowCodeCopyButtons= true

[services]
  [services.googleAnalytics]
    id = "G-4BN5LK4X9N"

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = false